### PR TITLE
Update multipass.md

### PR DESCRIPTION
**Pull request by andrewgoldfarb**
Add table for E.multipass.5

### CODE REVIEW

**Review by laszewsk — COMMENTED** [review]
what os?

you are overwriting others solutions

**Comment by andrewgoldfarb** [comment]
@laszewsk Mac OSX, I thought I was pushing to my repo's master branch only. Where am I overwriting others solutions? I would like to stop that and do it properly as soon as possible.

**Comment by laszewsk** [comment]
yes you di, but than the issue is if you do your local copy it is not contributing back to the class ...

also if someone else makes a chnage than you get a conflisct.

This is a good exercise in making sure that even if you do it locally you need to consider other peoples OS. Labeling your os xolution will solve this ;-) so its just one line diffeerence

**Comment by andrewgoldfarb** [comment]
Ok, I believe I understand, I'll update my copy accordingly and ask any questions in the meeting this week. Thank you!

**Pull request merged**
